name: Test Workflow

on:
  push:
    branches:
      - dev

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print message
        run: echo "Workflow triggered!"
